---
application:
  name: "img"
  project: "php img"
  organization: "QoveryCommunity"
  storage:
  - name: "img"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/img"
routers:
- name: "main-img"
  routes:
  - application_name: "img"
    paths:
    - "/*"
